'use client';

import React, { useState, useMemo, useEffect } from 'react';
import { X, BookmarkPlus, Sparkles, CheckSquare, Square } from 'lucide-react';
import { CustomGroup } from '@/types/database';
import {
  CustomOptionPreset,
  generateAutoPresetName,
  saveCustomOptionPreset,
} from '@/lib/customOptionPresets';

interface SaveCustomPresetModalProps {
  isOpen: boolean;
  onClose: () => void;
  groups: CustomGroup[];
  onSaveSuccess?: (preset: CustomOptionPreset) => void;
}

export function SaveCustomPresetModal({
  isOpen,
  onClose,
  groups,
  onSaveSuccess,
}: SaveCustomPresetModalProps) {
  const [nameInput, setNameInput] = useState('');
  const [descInput, setDescInput] = useState('');
  const [selectedGroupIds, setSelectedGroupIds] = useState<string[]>([]);

  useEffect(() => {
    if (isOpen) {
      setNameInput('');
      setDescInput('');
      setSelectedGroupIds(groups.map((g) => g.id));
    }
  }, [isOpen, groups]);

  const activeGroupsToSave = useMemo(() => {
    return groups.filter((g) => selectedGroupIds.includes(g.id));
  }, [groups, selectedGroupIds]);

  const autoGeneratedName = useMemo(() => {
    return generateAutoPresetName(activeGroupsToSave);
  }, [activeGroupsToSave]);

  const handleToggleGroup = (id: string) => {
    setSelectedGroupIds((prev) =>
      prev.includes(id) ? prev.filter((item) => item !== id) : [...prev, id]
    );
  };

  const handleSave = (e: React.FormEvent) => {
    e.preventDefault();
    if (activeGroupsToSave.length === 0) return;

    const saved = saveCustomOptionPreset(activeGroupsToSave, nameInput, descInput);
    if (onSaveSuccess) {
      onSaveSuccess(saved);
    }
    onClose();
  };

  if (!isOpen) return null;

  return (
    <div
      role="dialog"
      aria-modal="true"
      className="fixed inset-0 z-[120] flex items-center justify-center p-4 bg-slate-950/70 backdrop-blur-xs animate-in fade-in duration-150"
    >
      <div className="bg-white dark:bg-[#131B2B] rounded-3xl max-w-md w-full overflow-hidden shadow-2xl border border-slate-100 dark:border-slate-800 animate-in zoom-in-95 duration-150 text-slate-800 dark:text-slate-100 flex flex-col">
        {/* 頂部標題列 */}
        <div className="p-5 border-b border-slate-100 dark:border-slate-800 flex items-center justify-between bg-gradient-to-r from-sky-500/10 via-transparent to-transparent">
          <div className="flex items-center gap-2.5">
            <div className="w-10 h-10 rounded-2xl bg-sky-500/10 dark:bg-sky-500/20 text-sky-600 dark:text-sky-400 flex items-center justify-center">
              <BookmarkPlus className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-base font-extrabold text-slate-900 dark:text-slate-100">
                儲存為常用客製範本
              </h3>
              <p className="text-xs text-slate-400">將這套規格存入範本庫，未來任何商品皆可一鍵套用</p>
            </div>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="p-1.5 text-slate-400 hover:text-slate-600 dark:hover:text-slate-200 rounded-xl hover:bg-slate-100 dark:hover:bg-slate-800 transition cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* 表單內容 */}
        <form onSubmit={handleSave} className="p-5 space-y-4">
          {/* 範本名稱（選填） */}
          <div className="space-y-1.5">
            <div className="flex items-center justify-between">
              <label htmlFor="preset-name" className="text-xs font-extrabold text-slate-700 dark:text-slate-300">
                範本名稱 <span className="text-slate-400 font-normal">(選填)</span>
              </label>
              <span className="text-[11px] text-sky-600 dark:text-sky-400 font-bold flex items-center gap-1">
                <Sparkles className="w-3 h-3" />
                <span>留空將智慧命名</span>
              </span>
            </div>
            <input
              id="preset-name"
              type="text"
              placeholder={`預設：${autoGeneratedName}`}
              value={nameInput}
              onChange={(e) => setNameInput(e.target.value)}
              className="w-full bg-slate-50 dark:bg-[#182234] border border-slate-200 dark:border-slate-700 text-slate-800 dark:text-slate-100 placeholder:text-slate-400 dark:placeholder:text-slate-500 rounded-xl py-2 px-3 text-xs font-bold focus:outline-none focus:ring-2 focus:ring-sky-400"
            />
            <p className="text-[11px] text-slate-400 leading-relaxed">
              若未輸入名稱，系統將自動命名為「{autoGeneratedName}」。
            </p>
          </div>

          {/* 勾選欲儲存的規格群組 */}
          {groups.length > 1 && (
            <div className="space-y-2">
              <label className="text-xs font-extrabold text-slate-700 dark:text-slate-300">
                選擇欲包含在此範本中的規格組：
              </label>
              <div className="space-y-1.5 max-h-40 overflow-y-auto pr-1">
                {groups.map((grp) => {
                  const isChecked = selectedGroupIds.includes(grp.id);
                  return (
                    <button
                      key={grp.id}
                      type="button"
                      onClick={() => handleToggleGroup(grp.id)}
                      className={`w-full p-2 rounded-xl text-left border transition flex items-center justify-between text-xs cursor-pointer ${
                        isChecked
                          ? 'bg-sky-50/70 dark:bg-sky-950/40 border-sky-300 dark:border-sky-800 text-sky-900 dark:text-sky-200 font-bold'
                          : 'bg-slate-50 dark:bg-[#182234] border-slate-200 dark:border-slate-700 text-slate-500 opacity-60'
                      }`}
                    >
                      <span>
                        {grp.title || '未命名規格'} ({grp.options.length} 項選項)
                      </span>
                      {isChecked ? (
                        <CheckSquare className="w-4 h-4 text-sky-500 shrink-0" />
                      ) : (
                        <Square className="w-4 h-4 text-slate-400 shrink-0" />
                      )}
                    </button>
                  );
                })}
              </div>
            </div>
          )}

          {/* 簡介說明 (選填) */}
          <div className="space-y-1.5">
            <label htmlFor="preset-desc" className="text-xs font-extrabold text-slate-700 dark:text-slate-300">
              範本備註說明 <span className="text-slate-400 font-normal">(選填)</span>
            </label>
            <input
              id="preset-desc"
              type="text"
              placeholder="例如：適用於全店冷熱飲品、招牌特調"
              value={descInput}
              onChange={(e) => setDescInput(e.target.value)}
              className="w-full bg-slate-50 dark:bg-[#182234] border border-slate-200 dark:border-slate-700 text-slate-800 dark:text-slate-100 placeholder:text-slate-400 dark:placeholder:text-slate-500 rounded-xl py-2 px-3 text-xs font-medium focus:outline-none focus:ring-2 focus:ring-sky-400"
            />
          </div>

          {/* 按鈕區 */}
          <div className="flex gap-2 pt-2 border-t border-slate-100 dark:border-slate-800">
            <button
              type="button"
              onClick={onClose}
              className="flex-1 bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-300 font-bold py-2.5 rounded-xl text-xs transition cursor-pointer"
            >
              取消
            </button>
            <button
              type="submit"
              disabled={activeGroupsToSave.length === 0}
              className="flex-1 bg-sky-500 hover:bg-sky-600 disabled:opacity-50 text-white font-black py-2.5 rounded-xl text-xs shadow-xs transition active:scale-95 cursor-pointer flex items-center justify-center gap-1"
            >
              <BookmarkPlus className="w-3.5 h-3.5" />
              <span>確認儲存至範本庫</span>
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
